[General]
# Shadowrocket: Use in US (Trans)--pay attention to direct/proxy (reject should remain unchanged)
# this file serves as an aggregator; edit individual list files if needed
bypass-system = true
skip-proxy = 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, e.crashlytics.com, captive.apple.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server = system
ipv6 = true
prefer-ipv6 = false
private-ip-answer = true
update-url = https://raw.githubusercontent.com/superkeyor/ShadowrocketRules/master/@usa.conf

[Rule]
# DOMAIN-SET --> simply domains; RULE-SET --> DOMAIN-KEYWORD, DOMAIN-SUFFIX, IP-CIDR etc
# likely matches by listing order here (?)

# WhiteList (special cases to allow)
RULE-SET,https://raw.githubusercontent.com/superkeyor/ShadowrocketRules/master/Ruleset/WhiteList.list,DIRECT
# BlackList (special cases block)
RULE-SET,https://raw.githubusercontent.com/superkeyor/ShadowrocketRules/master/Ruleset/BlackList.list,REJECT
# Advertising
RULE-SET,https://raw.githubusercontent.com/superkeyor/ShadowrocketRules/master/Ruleset/Advertising.list,REJECT

# AppleOS Update
RULE-SET,https://raw.githubusercontent.com/superkeyor/ShadowrocketRules/master/Ruleset/AppleOS_Update.list,REJECT
# Privacy
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Privacy/Privacy_Domain.list,REJECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Privacy/Privacy.list,REJECT
# Hijacking
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Hijacking/Hijacking.list,REJECT

# https://github.com/Hackl0us/GeoIP2-CN
# DOMAIN-SUFFIX,cn,DIRECT
# GEOIP,CN,DIRECT

# reference: https://github.com/PaPerseller/chn-iplist/blob/master/Shadowrocket.conf
# https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Shadowrocket/ChinaMax
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaMax/ChinaMax_Domain.list,PROXY
# this rule set contains no-resolve already
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaMax/ChinaMax.list,PROXY

FINAL,DIRECT

[Host]

[URL Rewrite]
# Redirect Google Search Service
^(http|https):\/\/(www.)?(g|google)\.cn https://www.google.com 302
# Redirect Google Maps Service
^(http|https):\/\/(ditu|maps).google\.cn https://maps.google.com 302

[Script]
